object Form1: TForm1
  Left = 422
  Top = 240
  AlphaBlend = True
  AlphaBlendValue = 245
  BorderStyle = bsNone
  BorderWidth = 10
  Caption = 'WRS v0.2'
  ClientHeight = 757
  ClientWidth = 1184
  Color = clSilver
  Font.Charset = GB2312_CHARSET
  Font.Color = clAqua
  Font.Height = -35
  Font.Name = #31561#32447
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnKeyPress = FormKeyPress
  OnMouseMove = FormMouseMove
  PixelsPerInch = 96
  TextHeight = 36
  object SaveAndExit: TLabel
    Left = 760
    Top = 8
    Width = 210
    Height = 36
    Cursor = crHandPoint
    Hint = 'Save Progress and Exit'
    Caption = #20445#23384#28982#21518#36864#20986
    Color = clBackground
    ParentColor = False
    OnClick = SaveAndExitClick
  end
  object Label2: TLabel
    Left = 96
    Top = 8
    Width = 70
    Height = 36
    Cursor = crHandPoint
    Caption = #22797#20064
    Color = clDefault
    ParentColor = False
    OnClick = Label2Click
  end
  object Label4: TLabel
    Left = 200
    Top = 8
    Width = 140
    Height = 36
    Cursor = crHandPoint
    Caption = #24405#20837#21333#35789
    Color = clBackground
    ParentColor = False
    OnClick = Label4Click
  end
  object FormChooseTerm: TLabel
    Left = 552
    Top = 8
    Width = 70
    Height = 36
    Cursor = crHandPoint
    Caption = #36873#35789
    Color = clBackground
    ParentColor = False
    OnClick = FormChooseTermClick
  end
  object Label7: TLabel
    Left = 656
    Top = 8
    Width = 70
    Height = 36
    Cursor = crHandPoint
    Caption = #35774#32622
    Color = clBackground
    ParentColor = False
    OnClick = Label7Click
  end
  object Label9: TLabel
    Left = 376
    Top = 8
    Width = 140
    Height = 36
    Cursor = crHandPoint
    Caption = #28155#21152#27880#37322
    Color = clBackground
    ParentColor = False
    OnClick = Label9Click
  end
  object Panel1: TPanel
    Left = 432
    Top = 136
    Width = 713
    Height = 545
    Alignment = taLeftJustify
    BevelOuter = bvNone
    Color = clBlack
    TabOrder = 0
    object Label5: TLabel
      Left = 288
      Top = 441
      Width = 128
      Height = 67
      Cursor = crHandPoint
      Caption = #35748#35782
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -64
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
      OnClick = Label5Click
    end
    object Label3: TLabel
      Left = 537
      Top = 436
      Width = 128
      Height = 67
      Cursor = crHandPoint
      Caption = #24536#35760
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -64
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
      OnClick = Label3Click
    end
    object Label8: TLabel
      Left = 378
      Top = 48
      Width = 98
      Height = 36
      Alignment = taCenter
      Caption = 'Label8'
    end
    object TermInfoOutput: TLabel
      Left = 752
      Top = 48
      Width = 89
      Height = 14
      Caption = 'TermInfoOutput'
      Font.Charset = GB2312_CHARSET
      Font.Color = clAqua
      Font.Height = -13
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
    end
    object ErrorMessage: TLabel
      Left = 752
      Top = 0
      Width = 90
      Height = 15
      Caption = 'ErrorMessage'
      Font.Charset = GB2312_CHARSET
      Font.Color = clAqua
      Font.Height = -15
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
    end
    object Label19: TLabel
      Left = 216
      Top = 249
      Width = 384
      Height = 67
      Cursor = crHandPoint
      Caption = #28857#20987#26174#31034#35299#37322
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -64
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
      OnClick = Label19Click
    end
    object TestDef: TTntLabel
      Left = 192
      Top = 120
      Width = 80
      Height = 27
      Caption = 'TestDef'
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -24
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object TestPos: TTntLabel
      Left = 50
      Top = 120
      Width = 107
      Height = 27
      Alignment = taRightJustify
      Caption = 'TntLabel2'
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -24
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object TestSen: TTntLabel
      Left = 192
      Top = 232
      Width = 71
      Height = 23
      Caption = 'TestSen'
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -20
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label22: TLabel
      Left = 72
      Top = 441
      Width = 128
      Height = 67
      Cursor = crHandPoint
      Caption = #29087#30693
      Font.Charset = ANSI_CHARSET
      Font.Color = clTeal
      Font.Height = -64
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
      OnClick = Label22Click
    end
  end
  object Panel2: TPanel
    Left = 8
    Top = 520
    Width = 153
    Height = 153
    BevelOuter = bvNone
    Color = clBackground
    TabOrder = 1
    object Label11: TLabel
      Left = 72
      Top = 32
      Width = 140
      Height = 36
      Caption = #28155#21152#21333#35789
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -35
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
    end
    object SingleInsert: TLabel
      Left = 472
      Top = 80
      Width = 140
      Height = 36
      Caption = #21333#20010#28155#21152
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -35
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
      OnClick = SingleInsertClick
    end
    object MultipleInsert: TLabel
      Left = 472
      Top = 136
      Width = 140
      Height = 36
      Caption = #22810#34892#28155#21152
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -35
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
      OnClick = MultipleInsertClick
    end
    object FullInsert: TLabel
      Left = 480
      Top = 344
      Width = 140
      Height = 36
      Caption = #23436#25972#28155#21152
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -35
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
    end
    object LabelTerm: TLabel
      Left = 368
      Top = 368
      Width = 59
      Height = 16
      Caption = 'LabelTerm'
      Font.Charset = ANSI_CHARSET
      Font.Color = clSilver
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label1: TLabel
      Left = 368
      Top = 416
      Width = 94
      Height = 16
      Caption = '(Part of Speech)'
      Font.Charset = ANSI_CHARSET
      Font.Color = clSilver
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label18: TLabel
      Left = 368
      Top = 464
      Width = 53
      Height = 16
      Caption = 'Definition'
      Font.Charset = ANSI_CHARSET
      Font.Color = clSilver
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label20: TLabel
      Left = 600
      Top = 512
      Width = 94
      Height = 16
      Caption = 'Model Sentence'
      Font.Charset = ANSI_CHARSET
      Font.Color = clSilver
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label21: TLabel
      Left = 600
      Top = 560
      Width = 71
      Height = 16
      Caption = '(Translation)'
      Font.Charset = ANSI_CHARSET
      Font.Color = clSilver
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label6: TLabel
      Left = 624
      Top = 360
      Width = 128
      Height = 16
      Caption = #23436#25972#28155#21152#26242#19981#21487#29992
      Font.Charset = ANSI_CHARSET
      Font.Color = clSilver
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Edit1: TEdit
      Left = 240
      Top = 32
      Width = 65
      Height = 35
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -24
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      Text = 'Term'
      OnClick = Edit1Click
    end
    object Edit2: TEdit
      Left = 312
      Top = 32
      Width = 121
      Height = 35
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -24
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      Text = 'Definition'
    end
    object Memo1: TMemo
      Left = 448
      Top = 32
      Width = 185
      Height = 33
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        'Model sentence')
      ParentFont = False
      TabOrder = 2
    end
    object TntTerm: TTntEdit
      Left = 64
      Top = 80
      Width = 129
      Height = 41
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      Text = 'Term'
      OnClick = TntTermClick
    end
    object TNTList: TTntMemo
      Left = 64
      Top = 136
      Width = 289
      Height = 177
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        'Term1`(Definition1)'
        'Term2`(Definition2)'
        '...')
      ParentFont = False
      TabOrder = 5
      WordWrap = False
      OnClick = TNTListClick
    end
    object TntEdit2: TTntEdit
      Left = 64
      Top = 344
      Width = 289
      Height = 41
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 6
      Text = 'Term'
      OnClick = TntEdit2Click
    end
    object TntEdit3: TTntEdit
      Left = 64
      Top = 392
      Width = 289
      Height = 41
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 7
      Text = 'Part of Speech'
    end
    object TntEdit4: TTntEdit
      Left = 64
      Top = 440
      Width = 289
      Height = 41
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 8
      Text = 'Definition'
    end
    object TntEdit5: TTntEdit
      Left = 64
      Top = 488
      Width = 521
      Height = 41
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 9
      Text = 'Model Sentence'
    end
    object TntEdit6: TTntEdit
      Left = 64
      Top = 536
      Width = 521
      Height = 41
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 10
      Text = 'Translation'
    end
    object TntDef: TTntEdit
      Left = 208
      Top = 80
      Width = 145
      Height = 41
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
      Text = 'Definition'
    end
  end
  object Panel3: TPanel
    Left = 264
    Top = 96
    Width = 153
    Height = 153
    Alignment = taLeftJustify
    BevelOuter = bvNone
    Color = clBlack
    TabOrder = 2
    object Label14: TLabel
      Left = 74
      Top = 32
      Width = 175
      Height = 36
      Alignment = taCenter
      Caption = #32534#36753#21333#35789#34920
      Font.Charset = GB2312_CHARSET
      Font.Color = clAqua
      Font.Height = -35
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
    end
    object DeleteByIndex: TLabel
      Left = 730
      Top = 392
      Width = 173
      Height = 36
      Alignment = taCenter
      Caption = #21024#38500#25351#23450'ID'
      Font.Charset = GB2312_CHARSET
      Font.Color = clAqua
      Font.Height = -35
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
      OnClick = DeleteByIndexClick
    end
    object Label17: TLabel
      Left = 762
      Top = 448
      Width = 140
      Height = 36
      Alignment = taCenter
      Caption = #28155#21152#24050#36873
      Font.Charset = GB2312_CHARSET
      Font.Color = clAqua
      Font.Height = -35
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
    end
    object RDBName: TLabel
      Left = 258
      Top = 48
      Width = 18
      Height = 16
      Alignment = taCenter
      Caption = 'DB'
      Font.Charset = ANSI_CHARSET
      Font.Color = clSilver
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Edit4: TEdit
      Left = 808
      Top = 336
      Width = 89
      Height = 35
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -24
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      Text = 'Index'
    end
    object StringGrid1: TStringGrid
      Left = 24
      Top = 96
      Width = 641
      Height = 425
      BorderStyle = bsNone
      Color = clGray
      ColCount = 3
      DefaultColWidth = 200
      FixedColor = clBackground
      Font.Charset = GB2312_CHARSET
      Font.Color = clAqua
      Font.Height = -15
      Font.Name = #31561#32447
      Font.Style = []
      GridLineWidth = 2
      ParentFont = False
      ScrollBars = ssVertical
      TabOrder = 1
    end
  end
  object Panel4: TPanel
    Left = 8
    Top = 352
    Width = 153
    Height = 153
    Alignment = taLeftJustify
    BevelOuter = bvNone
    Color = clBlack
    TabOrder = 3
    object Label15: TLabel
      Left = 410
      Top = 48
      Width = 70
      Height = 36
      Alignment = taCenter
      Caption = #35774#32622
    end
    object Label12: TLabel
      Left = 528
      Top = 416
      Width = 70
      Height = 36
      Cursor = crHandPoint
      Caption = #30830#23450
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -35
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
      OnClick = Label12Click
    end
    object Label13: TLabel
      Left = 88
      Top = 136
      Width = 210
      Height = 36
      Cursor = crHandPoint
      Caption = #26032#28155#21333#35789#25968#37327
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -35
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
    end
    object Edit3: TEdit
      Left = 472
      Top = 136
      Width = 89
      Height = 35
      BorderStyle = bsNone
      Color = cl3DDkShadow
      TabOrder = 0
      Text = '50'
    end
  end
  object Panel5: TPanel
    Left = 8
    Top = 192
    Width = 153
    Height = 145
    BevelOuter = bvNone
    Color = clBackground
    TabOrder = 4
    object Label10: TLabel
      Left = 72
      Top = 32
      Width = 140
      Height = 36
      Caption = #28155#21152#27880#37322
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -35
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
    end
    object Label23: TLabel
      Left = 712
      Top = 464
      Width = 70
      Height = 36
      Caption = #28155#21152
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -35
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
    end
    object Label24: TLabel
      Left = 360
      Top = 168
      Width = 59
      Height = 16
      Caption = 'LabelTerm'
      Font.Charset = ANSI_CHARSET
      Font.Color = clSilver
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label25: TLabel
      Left = 360
      Top = 336
      Width = 94
      Height = 16
      Caption = '(Part of Speech)'
      Font.Charset = ANSI_CHARSET
      Font.Color = clSilver
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label26: TLabel
      Left = 360
      Top = 384
      Width = 53
      Height = 16
      Caption = 'Definition'
      Font.Charset = ANSI_CHARSET
      Font.Color = clSilver
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label27: TLabel
      Left = 592
      Top = 432
      Width = 94
      Height = 16
      Caption = 'Model Sentence'
      Font.Charset = ANSI_CHARSET
      Font.Color = clSilver
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label28: TLabel
      Left = 592
      Top = 480
      Width = 71
      Height = 16
      Caption = '(Translation)'
      Font.Charset = ANSI_CHARSET
      Font.Color = clSilver
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label16: TLabel
      Left = 168
      Top = 112
      Width = 73
      Height = 14
      Cursor = crDrag
      Caption = #25353'J/K'#26469#21152'/'#20943
      Font.Charset = ANSI_CHARSET
      Font.Color = clSilver
      Font.Height = -13
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
    end
    object TntEdit7: TTntEdit
      Left = 56
      Top = 144
      Width = 289
      Height = 41
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      Text = 'Term'
      OnClick = TntEdit7Click
    end
    object TntEdit8: TTntEdit
      Left = 56
      Top = 312
      Width = 289
      Height = 41
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      Text = 'Part of Speech'
    end
    object TntEdit9: TTntEdit
      Left = 56
      Top = 360
      Width = 289
      Height = 41
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      Text = 'Definition'
    end
    object TntEdit10: TTntEdit
      Left = 56
      Top = 408
      Width = 521
      Height = 41
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      Text = 'Model Sentence'
    end
    object TntEdit11: TTntEdit
      Left = 56
      Top = 456
      Width = 521
      Height = 41
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
      Text = 'Translation'
    end
    object TntEdit1: TTntEdit
      Left = 56
      Top = 88
      Width = 105
      Height = 41
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
      Text = 'TermID'
      OnChange = TntEdit1Change
      OnClick = TntEdit1Click
      OnKeyPress = TntEdit1KeyPress
    end
  end
  object ZConnection1: TZConnection
    ControlsCodePage = cGET_ACP
    UTF8StringsAsWideField = False
    AutoEncodeStrings = False
    HostName = '127.0.0.1'
    Port = 3306
    Database = 'Terms'
    User = 'root'
    Password = 'sirisoak'
    Protocol = 'mysqld-5'
    Left = 8
    Top = 688
  end
  object ZTable1: TZTable
    Connection = ZConnection1
    TableName = 'test'
    Left = 48
    Top = 688
  end
  object DataSource1: TDataSource
    DataSet = ZQuery1
    Left = 88
    Top = 688
  end
  object ZQuery1: TZQuery
    Connection = ZConnection1
    Params = <>
    Left = 128
    Top = 688
  end
  object ZQuery2: TZQuery
    Connection = ZConnection1
    Params = <>
    Left = 128
    Top = 720
  end
  object DataSource2: TDataSource
    DataSet = ZQuery2
    Left = 88
    Top = 720
  end
end
