object Form1: TForm1
  Left = 180
  Top = 151
  AlphaBlend = True
  AlphaBlendValue = 245
  BorderStyle = bsToolWindow
  BorderWidth = 10
  Caption = 'WRS v0.1'
  ClientHeight = 757
  ClientWidth = 1184
  Color = clSilver
  Font.Charset = GB2312_CHARSET
  Font.Color = clAqua
  Font.Height = -35
  Font.Name = #31561#32447
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  PixelsPerInch = 96
  TextHeight = 36
  object Label1: TLabel
    Left = 760
    Top = -24
    Width = 210
    Height = 36
    Cursor = crHandPoint
    Hint = 'Save Progress and Exit'
    Caption = #20445#23384#28982#21518#36864#20986
    Color = clBackground
    ParentColor = False
    OnClick = Label1Click
  end
  object Label2: TLabel
    Left = 96
    Top = -24
    Width = 70
    Height = 36
    Cursor = crHandPoint
    Caption = #22797#20064
    Color = clDefault
    ParentColor = False
    OnClick = Label2Click
  end
  object Label4: TLabel
    Left = 216
    Top = -24
    Width = 140
    Height = 36
    Cursor = crHandPoint
    Caption = #24405#20837#21333#35789
    Color = clBackground
    ParentColor = False
    OnClick = Label4Click
  end
  object Label6: TLabel
    Left = 400
    Top = -24
    Width = 70
    Height = 36
    Cursor = crHandPoint
    Caption = #36873#35789
    Color = clBackground
    ParentColor = False
    OnClick = Label6Click
  end
  object Label7: TLabel
    Left = 520
    Top = -24
    Width = 70
    Height = 36
    Cursor = crHandPoint
    Caption = #35774#32622
    Color = clBackground
    ParentColor = False
    OnClick = Label7Click
  end
  object Panel1: TPanel
    Left = 208
    Top = 88
    Width = 897
    Height = 561
    Alignment = taLeftJustify
    BevelOuter = bvNone
    Color = clBlack
    TabOrder = 0
    object Label5: TLabel
      Left = 120
      Top = 441
      Width = 128
      Height = 67
      Cursor = crHandPoint
      Caption = #35748#35782
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -64
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
      OnClick = Label5Click
    end
    object Label3: TLabel
      Left = 537
      Top = 436
      Width = 128
      Height = 67
      Cursor = crHandPoint
      Caption = #24536#35760
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -64
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
      OnClick = Label3Click
    end
    object Label8: TLabel
      Left = 378
      Top = 48
      Width = 98
      Height = 36
      Alignment = taCenter
      Caption = 'Label8'
    end
    object Label9: TLabel
      Left = 88
      Top = 136
      Width = 98
      Height = 36
      Caption = 'Label9'
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -35
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
    end
    object Label10: TLabel
      Left = 88
      Top = 200
      Width = 51
      Height = 15
      Caption = 'Label10'
      Font.Charset = GB2312_CHARSET
      Font.Color = clAqua
      Font.Height = -15
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
    end
    object TermInfoOutput: TLabel
      Left = 616
      Top = 48
      Width = 89
      Height = 14
      Caption = 'TermInfoOutput'
      Font.Charset = GB2312_CHARSET
      Font.Color = clAqua
      Font.Height = -13
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
    end
    object ErrorMessage: TLabel
      Left = 616
      Top = 0
      Width = 90
      Height = 15
      Caption = 'ErrorMessage'
      Font.Charset = GB2312_CHARSET
      Font.Color = clAqua
      Font.Height = -15
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
    end
    object Label19: TLabel
      Left = 216
      Top = 249
      Width = 384
      Height = 67
      Cursor = crHandPoint
      Caption = #28857#20987#26174#31034#35299#37322
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -64
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
      OnClick = Label19Click
    end
  end
  object Panel2: TPanel
    Left = 8
    Top = 184
    Width = 153
    Height = 153
    Color = clBackground
    TabOrder = 1
    object Label11: TLabel
      Left = 72
      Top = 32
      Width = 140
      Height = 36
      Caption = #28155#21152#21333#35789
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -35
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
    end
    object Label18: TLabel
      Left = 592
      Top = 376
      Width = 70
      Height = 36
      Caption = #28155#21152
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -35
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
      OnClick = Label18Click
    end
    object Edit1: TEdit
      Left = 72
      Top = 88
      Width = 329
      Height = 35
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -24
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      Text = 'Term'
      OnClick = Edit1Click
    end
    object Edit2: TEdit
      Left = 72
      Top = 144
      Width = 329
      Height = 35
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -24
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      Text = 'Definition'
    end
    object Memo1: TMemo
      Left = 72
      Top = 200
      Width = 441
      Height = 153
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = GB2312_CHARSET
      Font.Color = clAqua
      Font.Height = -21
      Font.Name = #31561#32447
      Font.Style = []
      Lines.Strings = (
        'Model sentence')
      ParentFont = False
      TabOrder = 2
    end
  end
  object Panel3: TPanel
    Left = 8
    Top = 520
    Width = 153
    Height = 153
    Alignment = taLeftJustify
    BevelOuter = bvNone
    Color = clBlack
    TabOrder = 2
    object Label14: TLabel
      Left = 74
      Top = 32
      Width = 175
      Height = 36
      Alignment = taCenter
      Caption = #32534#36753#21333#35789#34920
      Font.Charset = GB2312_CHARSET
      Font.Color = clAqua
      Font.Height = -35
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
    end
    object Label16: TLabel
      Left = 666
      Top = 392
      Width = 173
      Height = 36
      Alignment = taCenter
      Caption = #21024#38500#25351#23450'ID'
      Font.Charset = GB2312_CHARSET
      Font.Color = clAqua
      Font.Height = -35
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
      OnClick = Label16Click
    end
    object Label17: TLabel
      Left = 706
      Top = 448
      Width = 140
      Height = 36
      Alignment = taCenter
      Caption = #28155#21152#24050#36873
      Font.Charset = GB2312_CHARSET
      Font.Color = clAqua
      Font.Height = -35
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
    end
    object Edit4: TEdit
      Left = 752
      Top = 336
      Width = 89
      Height = 35
      BorderStyle = bsNone
      Color = cl3DDkShadow
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -24
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      Text = 'Index'
    end
    object Edit5: TEdit
      Left = 368
      Top = 24
      Width = 145
      Height = 27
      Font.Charset = GB2312_CHARSET
      Font.Color = clAqua
      Font.Height = -19
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      Text = 'Edit5'
    end
    object StringGrid1: TStringGrid
      Left = 24
      Top = 96
      Width = 625
      Height = 409
      BorderStyle = bsNone
      Color = clGray
      ColCount = 3
      DefaultColWidth = 200
      FixedColor = clBackground
      Font.Charset = GB2312_CHARSET
      Font.Color = clAqua
      Font.Height = -15
      Font.Name = #31561#32447
      Font.Style = []
      GridLineWidth = 2
      ParentFont = False
      ScrollBars = ssVertical
      TabOrder = 2
    end
    object Edit6: TEdit
      Left = 368
      Top = 64
      Width = 145
      Height = 27
      Font.Charset = GB2312_CHARSET
      Font.Color = clAqua
      Font.Height = -19
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      Text = 'Edit6'
    end
  end
  object Panel4: TPanel
    Left = 8
    Top = 352
    Width = 153
    Height = 153
    Alignment = taLeftJustify
    BevelOuter = bvNone
    Color = clBlack
    TabOrder = 3
    object Label15: TLabel
      Left = 410
      Top = 48
      Width = 70
      Height = 36
      Alignment = taCenter
      Caption = #35774#32622
    end
    object Label12: TLabel
      Left = 528
      Top = 416
      Width = 70
      Height = 36
      Cursor = crHandPoint
      Caption = #30830#23450
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -35
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
      OnClick = Label12Click
    end
    object Label13: TLabel
      Left = 88
      Top = 136
      Width = 210
      Height = 36
      Cursor = crHandPoint
      Caption = #26032#28155#21333#35789#25968#37327
      Font.Charset = ANSI_CHARSET
      Font.Color = clAqua
      Font.Height = -35
      Font.Name = #31561#32447
      Font.Style = []
      ParentFont = False
    end
    object Edit3: TEdit
      Left = 472
      Top = 136
      Width = 89
      Height = 35
      BorderStyle = bsNone
      Color = cl3DDkShadow
      TabOrder = 0
      Text = '50'
    end
  end
  object ZConnection1: TZConnection
    ControlsCodePage = cGET_ACP
    UTF8StringsAsWideField = False
    AutoEncodeStrings = False
    Connected = True
    HostName = '127.0.0.1'
    Port = 3306
    Database = 'Terms'
    User = 'root'
    Password = 'sirisoak'
    Protocol = 'mysqld-5'
    LibraryLocation = 'D:\DelphiLarry\00 Delphi Memo\libmysql_5.dll'
    Left = 8
    Top = 688
  end
  object ZTable1: TZTable
    Connection = ZConnection1
    TableName = 'test'
    Left = 48
    Top = 688
  end
  object DataSource1: TDataSource
    DataSet = ZQuery1
    Left = 88
    Top = 688
  end
  object ZQuery1: TZQuery
    Connection = ZConnection1
    Params = <>
    Left = 128
    Top = 688
  end
  object ZQuery2: TZQuery
    Connection = ZConnection1
    Params = <>
    Left = 128
    Top = 720
  end
  object DataSource2: TDataSource
    DataSet = ZQuery2
    Left = 88
    Top = 720
  end
end
